server.port: 8085

#dbValues: "{connectionString:'http://___',userName:'user',password:'pass'}"

management.endpoints.web.exposure.include : "*"
spring.profiles.active: test

app:
    name: My App
    description: Welcome to ${app.name}

spring.cloud.config.url: http://localhost:8086
spring.application.name: spring-boot-config